name: CI

on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "**/*.md"
      - "LICENSE"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "**/*.md"
      - "LICENSE"

permissions: {}

jobs:
  test-suite:
    uses: ./.github/workflows/reusable-test.yml
